installClusterAgent: true

imageInfo:
  agentImage: docker.io/appdynamics/cluster-agent
  agentTag: latest
  operatorImage: docker.io/appdynamics/cluster-agent-operator
  operatorTag: latest
  imagePullPolicy: Always

controllerInfo:
  url: http://appdynamics.portoseguro.brasil:80
  account: customer1
  accessKey: 3ffed1d3-b5df-420b-a722-5cfa5e2388d8

agentServiceAccount: appdynamics-cluster-agent
operatorServiceAccount: appdynamics-operator

# Cluster agent config
clusterAgent:
  nsToMonitor:
    - amazon-guardduty
    - appdynamics
    - cienciadedados
    - default
    - fluentbit
    - ingress-nginx
    - kube-node-lease
    - kube-public
    - kube-system
    - kubecost
    - kubernetes-dashboard
    - test-connection
    - tools
    - twistlock
  appName: cienciadedados-prd

# helm upgrade --install appdynamics --namespace appdynamics appdynamics-charts/cluster-agent -f ./values-prd.yaml